"""add_user_note_to_leads

Revision ID: 2697a3a6df88
Revises: 5a8753094e0c
Create Date: 2026-05-01 13:04:33.820859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2697a3a6df88'
down_revision: Union[str, None] = '5a8753094e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('leads', sa.Column('user_note', sa.Text(), nullable=False, server_default=''))
    op.alter_column('leads', 'user_note', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'user_note')
    # ### end Alembic commands ###
